2025-08-06 21:47:42,972 [INFO] Start polling
2025-08-06 21:47:43,672 [INFO] Run polling for bot @vlalistabot id=8318772952 - 'ALISTA Customs'
2025-08-06 21:47:51,086 [INFO] Update id=505441847 is handled. Duration 1997 ms by bot id=8318772952
2025-08-06 21:47:52,779 [INFO] Update id=505441848 is handled. Duration 219 ms by bot id=8318772952
2025-08-06 21:51:07,741 [INFO] Start polling
2025-08-06 21:51:10,083 [INFO] Run polling for bot @vlalistabot id=8318772952 - 'ALISTA Customs'
2025-08-06 21:51:12,533 [INFO] Update id=505441849 is handled. Duration 1444 ms by bot id=8318772952
2025-08-06 21:51:13,487 [INFO] Update id=505441850 is handled. Duration 615 ms by bot id=8318772952
2025-08-06 21:51:17,082 [INFO] Update id=505441851 is handled. Duration 630 ms by bot id=8318772952
2025-08-06 21:51:19,301 [INFO] Update id=505441852 is handled. Duration 219 ms by bot id=8318772952
2025-08-06 21:51:24,027 [INFO] Update id=505441853 is handled. Duration 945 ms by bot id=8318772952
2025-08-06 21:51:27,643 [INFO] Update id=505441854 is handled. Duration 273 ms by bot id=8318772952
2025-08-06 21:51:36,325 [INFO] Update id=505441855 is handled. Duration 314 ms by bot id=8318772952
2025-08-06 21:51:39,474 [INFO] Update id=505441856 is handled. Duration 312 ms by bot id=8318772952
2025-08-06 21:51:47,446 [WARNING] Попытка 1 не удалась: cannot access local variable 'eur_rate' where it is not associated with a value
2025-08-06 21:51:52,472 [WARNING] Попытка 2 не удалась: cannot access local variable 'eur_rate' where it is not associated with a value
2025-08-06 21:51:59,477 [WARNING] Попытка 3 не удалась: HTTPSConnectionPool(host='www.cbr.ru', port=443): Read timed out. (read timeout=5)
2025-08-06 21:51:59,477 [ERROR] Не удалось получить курс евро после всех попыток
2025-08-06 21:52:00,225 [INFO] Update id=505441857 is handled. Duration 16142 ms by bot id=8318772952
2025-08-06 21:52:27,085 [WARNING] Попытка 1 не удалась: cannot access local variable 'eur_rate' where it is not associated with a value
2025-08-06 21:52:32,084 [WARNING] Попытка 2 не удалась: cannot access local variable 'eur_rate' where it is not associated with a value
2025-08-06 21:52:35,496 [WARNING] Попытка 3 не удалась: cannot access local variable 'eur_rate' where it is not associated with a value
2025-08-06 21:52:35,497 [ERROR] Не удалось получить курс евро после всех попыток
2025-08-06 21:52:36,362 [INFO] Update id=505441858 is handled. Duration 14279 ms by bot id=8318772952
2025-08-06 21:53:00,228 [INFO] Update id=505441859 is not handled. Duration 1 ms by bot id=8318772952
2025-08-06 21:53:00,228 [ERROR] Cause exception while process update id=505441859 by bot id=8318772952
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        observer=observer, update_type=update_type, event=telegram_event, **data
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        observer=observer, update_type=update_type, event=telegram_event, **data
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artur\AppData\Roaming\Python\Python313\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\Artur\Desktop\py\bot_alista\handlers\calculate.py", line 178, in send_pdf_report_to_user
    generate_calculation_pdf(result, data, pdf_path)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Artur\Desktop\py\bot_alista\services\pdf_report.py", line 47, in generate_calculation_pdf
    pdf.cell(0, 8, f"Цена: {result.get('price_eur', '')} €", ln=True)
                            ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
